name: variant
version: 2.5.0
description: Roslin Variant Pipeline v2.5.0
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
    - /opt
env:
  TOIL_LSF_ARGS: '-S 1 -We 0:59'
  TMPDIR: '/scratch'
  TMP: '/scratch'
dependencies:
  core:
    version:
      min: 2.1.0
      max: 2.1.0
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/roslin-cmo/1.9.10/cmo
  singularity:
    version: 3.0.3
    install-path: /opt/common/CentOS_6-dev/singularity/singularity-3.0.3/bin/singularity
  toil:
    version: 3.18.0-release
    install-path: /ifs/work/pi/roslin-toil/3.18.0-release
test:
  root: /ifs/work/pi/roslin-test
  batchsystem: singleMachine
  cwlBatchsystem: singleMachine
  tempDir: /ifs/work/pi/roslin-test/scratch/
  runArgs: '--on-success /ifs/work/pi/roslin-internal-services/roslin-done.py --on-fail /ifs/work/pi/roslin-internal-services/roslin-fail.py'
  env:
    TOIL_LSF_ARGS: '-S 1 -We 0:59'
build:
  buildDocker: False
  buildSingularity: true
  dockerRegistry: 'mskcc'
  dockerPush: False
  installCore: true
  buildThreads: 1