name: variant
version: 2.0.0
description: Roslin Variant Pipeline v2.0.0
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.0
      max: 2.0.0
  cmo:
    version: 1.9.7
    install-path: /ifs/work/pi/cmo_package_archive/
