name: variant
version: 2.4.1
description: Roslin Variant Pipeline v2.5.0
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.5
      max: 2.0.5
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/roslin-cmo/1.9.10/cmo
  singularity:
    version: 2.5.1
    install-path: /opt/common/CentOS_6-dev/singularity/singularity-2.5.1/bin/singularity
  toil:
    version: 3.18.0a1-MSK
    install-path: /ifs/work/pi/roslin-toil/3.18.0a1-MSK/toil/
