name: variant
version: 1.0.0
description: Roslin Variant Pipeline v1.0.0
root: /ifs/work/pi/roslin-pipelines/variant
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 1.0.0
      max: 1.0.0
  cmo:
    version: 1.6.8
    python-path: /ifs/work/pi/cmo_package_archive/1.6.7/lib/python2.7/site-packages/
