--2019-06-14 13:52:55--  https://raw.githubusercontent.com/mskcc/roslin-variant/2.5.x/config.variant.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.248.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.248.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1534 (1.5K) [text/plain]
Saving to: ‘config.variant.yaml.1’

     0K .                                                     100%  206M=0s

2019-06-14 13:52:55 (206 MB/s) - ‘config.variant.yaml.1’ saved [1534/1534]

