name: variant
version: 2.5.0
description: Roslin Variant Pipeline v2.5.0
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
    - /opt
env:
  TOIL_LSF_ARGS: '-S 1 -We 0:59'
dependencies:
  core:
    version:
      min: 2.0.6
      max: 2.0.6
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/roslin-cmo/1.9.10/cmo
  singularity:
    version: 2.5.1
    install-path: /opt/common/CentOS_6-dev/singularity/singularity-2.5.1/bin/singularity
  toil:
    version: 3.17.0
    install-path: /ifs/work/pi/roslin-toil/3.17.0-release/
test:
  root: /ifs/work/pi/roslin-test
  tempDir: /scratch  
  runArgs:  --single-node --leader-node controlR
  env:
    TOIL_LSF_ARGS: '-S 1'
build:
  buildImages: true
  installCore: true
  buildThreads: 4
  vagrantSize: 80GB
