name: variants
version: 2.3.0
description: Roslin Variant Pipeline v2.3.0
root: /ifs/work/pi/roslin-pipelines-dev
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.3
      max: 2.0.3
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/cmo_package_archive/
test:
  root: /ifs/work/pi/roslin-test/
  tempDir: /scratch  
  runArgs: --single-node --leader-node largeHG
  env:
    TOIL_LSF_ARGS: '-S 1 -We 0:59 -R select[internet]'
build:
  buildImages: false
  installCore: true
  buildThreads: 4
  vagrantSize: 50GB
