name: variant
version: 2.4.2
description: Roslin Variant Pipeline v2.4.2
root: /ifs/work/pi/roslin-pipelines
binding:
  core: bin
  data: resources
  output: outputs
  workspace: workspace
  extra:
    - /scratch
    - /ifs
dependencies:
  core:
    version:
      min: 2.0.6
      max: 2.0.6
  cmo:
    version: 1.9.10
    install-path: /ifs/work/pi/cmo_package_archive/
test:
  root: /ifs/work/pi/roslin-test
  tempDir: /scratch  
  runArgs:  --single-node --leader-node controlR
  env:
    TOIL_LSF_ARGS: '-S 1'
build:
  buildImages: false
  installCore: true
  buildThreads: 4
  vagrantSize: 50GB
